import type { Metadata } from 'next';
import { fredoka } from './fonts/fonts';
import './globals.css';
import Header from './components/header';
import Footer from './components/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={fredoka.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
